### ISSUE TITLE
Image error when building

### ISSUE THREAD

**Issue by snowiware** [evanbowman/BPCore-Engine#8]
Hello, I have just started using this engine and I'm completely unsure of how to get the bmp spritesheets and tilesheets working. I'm assuming it has something to do with how the image is saved, as I got 2 different errors from multiple attempts.

_When exporting 24-bit or 256 color from Paint or Paint.net:_

```
lua: build.lua:196: bad argument #2 to 'pack' (unsigned overflow)
stack traceback:
        [C]: in function 'string.pack'
        build.lua:196: in function 'write_tile'
        build.lua:285: in function 'convert_tileset'
        build.lua:380: in main chunk
        [C]: in ?
```
_When converting and exporting 24-bit from Usenti:_

```
lua: build.lua:263: attempt to index a nil value (local 'img')
stack traceback:
        build.lua:263: in function 'convert_tileset'
        build.lua:380: in main chunk
        [C]: in ?
```

Tell me if more info is needed.

**Comment by evanbowman** [comment]
Sorry! As you noticed, I was not handling the errors from the image library correctly! Thanks for letting me know, I created a new release tag and patched the build script.

https://github.com/evanbowman/BPCore-Engine/commit/666a1ee97ebd89496cd64e87593c37be40e7c4a8

Some further tips:
This gba engine supports 16 color graphics. The gba hardware supports either 16 color or 256 color, and I chose 16 color because 256 color graphics use twice as much video ram, i.e. half as many sprite images. The gba hardware treats one of the color indices as a transparent color. In the build script, I hard-coded RGB(255, 0, 255) as the transparency color. See [here](https://github.com/evanbowman/BPCore-Engine/blob/666a1ee97ebd89496cd64e87593c37be40e7c4a8/build/build.lua#L280) and [here](https://github.com/evanbowman/BPCore-Engine/blob/666a1ee97ebd89496cd64e87593c37be40e7c4a8/build/build.lua#L315)
I can make the transparency color channel parameterizable when I have some free time, see those two links in the meantime if you want to change the default transparency color.

**Comment by evanbowman** [comment]
For the issue where you tried a 24 bit image, using the new version of build.lua from the release script will give you a more descriptive error. As the build script requires the 24-bit format of a BMP file, the bit depth would not be the issue, possibly, the bitmap file is using compression, which isn't supported by the build.lua script.

See here for all of the varieties of invalid bitmap format errors (which will now appear in the build error output):
https://github.com/evanbowman/BPCore-Engine/blob/master/build/build.lua#L36

**Comment by snowiware** [comment]
Thank you very much! And for the 24-bit BMPs, that was most likely an issue with the way it exported so that was probably on me.
